BEGIN;

-- Migration portavel para recriar o schema usado pelo app em provedores
-- PostgreSQL compativeis fora do Supabase.

CREATE TABLE IF NOT EXISTS projetos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bolsistas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    categoria TEXT NOT NULL DEFAULT 'Bolsista',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id BIGINT NOT NULL REFERENCES projetos(id) ON DELETE RESTRICT,
    descricao TEXT NOT NULL,
    responsaveis TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    status TEXT NOT NULL DEFAULT 'pendente',
    data_inicio DATE NOT NULL,
    prazo DATE,
    prioridade TEXT NOT NULL DEFAULT 'media',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT tarefas_status_check
        CHECK (status IN ('pendente', 'concluida', 'excluida')),
    CONSTRAINT tarefas_prioridade_check
        CHECK (prioridade IN ('alta', 'media', 'baixa')),
    CONSTRAINT tarefas_prazo_check
        CHECK (prazo IS NULL OR prazo >= data_inicio),
    CONSTRAINT tarefas_responsaveis_check
        CHECK (cardinality(responsaveis) > 0)
);

CREATE TABLE IF NOT EXISTS escalas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bolsista_id BIGINT NOT NULL REFERENCES bolsistas(id) ON DELETE CASCADE,
    dia_semana SMALLINT NOT NULL,
    hora_inicio SMALLINT NOT NULL,
    hora_fim SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT escalas_dia_semana_check
        CHECK (dia_semana BETWEEN 1 AND 5),
    CONSTRAINT escalas_hora_check
        CHECK (
            hora_inicio >= 0
            AND hora_fim <= 24
            AND hora_fim > hora_inicio
        ),
    CONSTRAINT escalas_slot_unique
        UNIQUE (bolsista_id, dia_semana, hora_inicio, hora_fim)
);

CREATE TABLE IF NOT EXISTS avisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto TEXT NOT NULL,
    data_exibicao DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pin_attempts (
    ip TEXT PRIMARY KEY,
    attempts INTEGER NOT NULL DEFAULT 0,
    blocked_until TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pin_attempts_attempts_check
        CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS idx_tarefas_status_created_at
    ON tarefas (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tarefas_projeto_id
    ON tarefas (projeto_id);

CREATE INDEX IF NOT EXISTS idx_tarefas_prazo
    ON tarefas (prazo);

CREATE INDEX IF NOT EXISTS idx_escalas_lookup
    ON escalas (dia_semana, hora_inicio, hora_fim);

CREATE INDEX IF NOT EXISTS idx_escalas_bolsista
    ON escalas (bolsista_id, dia_semana, hora_inicio);

CREATE INDEX IF NOT EXISTS idx_avisos_data_exibicao_created_at
    ON avisos (data_exibicao, created_at);

CREATE INDEX IF NOT EXISTS idx_pin_attempts_blocked_until
    ON pin_attempts (blocked_until);

COMMIT;
